data = {

    'Scale': '缩放',
    'Transform': '变换',
    'Options': '选项',
    'Animation': '动画',
    'Armature': '骨架',
    'Include': '包括',
    'Rotation': "旋转转换",
    'Rotation conversion': '旋转',
    'extract textures into folder': '提取纹理至文件夹',
    'make new texture folder': "创建新的纹理文件夹",
    'set shading type to material on import': '在导入时将着色类型设置为材质',
    'set view transform to standard on import': '在导入时将视图变换设置为标准',
    'set armature display to wire': '将骨骼显示设置为线框',
    'set armature display to show in front': '将骨骼显示设置为显示在前面',
    'set armature bone shape to default': '将骨骼骨头形状设置为默认',
    'File Name Collision': '文件名冲突',
    'Textures Directory': '贴图路径',
    'Behavior when the name of an imported texture file conflicts with an existing file': '在导入的纹理文件名与现有文件冲突时的行为',
    'Overwrite existing files': '覆盖已存在',
    'If a file with the same name already exists, use that instead of copying': '引用已有文件',
    'Path to the directory where imported textures will be copied': '导入纹理将被复制到的目录路径',
    'Behavior when importing textures from a USDZ archive': '从usd文件导入纹理时的行为',
    'Copy files to textures directory': '将文件复制到纹理目录',
    'Import textures as packed data': '将纹理导入为打包数据',
    "Don't import textures": '不导入纹理',
    'Behavior when the name of an imported material conflicts with an existing material': '当导入的材质名称与现有材质冲突时的行为',
    'If a material with the same name already exists, reference that instead of importing': "如果已存在同名材质，则引用该材质而不是导入",
    "Import each USD material as a unique Blender material": "将每个USD材质导入为一个独特的Blender材质",
    'Material Name Collision': "材质名称冲突",
    "If the Import USD Preview option is enabled,the material blend method will automatically be set based on the shader's opacity and opacityThreshold inputs": "如果启用了导入 USD 预览选项，则材质混合方法将根据着色器的不透明度和不透明度阈值输入自动设置",
    'Set Material Blend': '材质混合',
    'Convert UsdPreviewSurface shaders to Principled BSDF shader networks': '将UsdPreviewSurface着色器转换为Principled BSDF着色器网络',
    'Import USD Preview': '导入usd预览',
    "Also import materials that are not used by any geometry.Note that when this option is false, materials referenced by geometry will still be imported": "也导入未被任何几何体使用的材质。请注意，当此选项为false时，仍会导入几何体引用的材质",
    'Import All Materials': '导入所有材质',
    'Scale for the intensity of imported lights': "导入灯光强度的缩放比例",
    'Light Intensity Scale': '灯光强度缩放',
    'Add all imported objects to a new collection': "将所有导入的对象添加到一个新的集合中",
    'Create Collection': '创建集合',
    "Select the file relative to the blend file":"选择相对于 blend 文件的文件",
    "Update the scene's start and end frame to match those of the USD archive": '更新场景的起始帧和结束帧，使其与 USD 归档的相匹配',
    'set frame range': '设置帧范围',
    'Import final render geometry': '导入最终渲染几何体',
    'Render': '渲染',
    'Import proxy geometry': '导入代理几何体',
    'Proxy': '代理',
    'Import guide geometry': '导入引导几何体',
    'Guide': '引导',
    "Do not import invisible USD primitives.Only applies to primitives with a non-animated visibility attribute.Primitives with animated visibility will always be imported": '不导入不可见的USD基元。仅适用于具有非动画可见性属性的基元。具有动画可见性的基元将始终被导入',
    'Visible Primitives Only': '导入仅可见',
    'Create unique Blender objects for USD instances': "为USD实例创建唯一的Blender对象",
    'Import Instance Proxies': "导入实例代理",
    'Create subdivision surface modifiers based on the USD SubdivisionScheme attribute':  "根据USD SubdivisionScheme属性创建次表面细分修改器",
    'Import Subdivision Scheme': '导入细分方案',
    'Read USD Primvars as mesh attributes': '将USD Primvars读取为网格属性',
    'Mesh Attributes': '网格属性',
    'Read mesh color attributes':  "读取网格颜色属性",
    'Color Attributes': '颜色属性',
    'Read mesh UV coordinates': "读取网格UV坐标",
    'UV Coordinates': 'UV坐标',
    "Value by which to enlarge or shrink the objects with respect to the world's origin":  "相对于世界原点放大或缩小对象的值",
    'Import only the primitive at the given path and its descendants.Multiple paths may be specified in a list delimited by commas or semicolons': "仅导入给定路径及其子代的基元。可以在用逗号或分号分隔的列表中指定多个路径",
    'Path Mask': '路径遮罩',
    'Blend Shapes': '形态键',
    'Skeletons': '骨骼',
    'Volumes': '体积',
    'Meshes': '网格',
    'Materials': '材质',
    'Lights': '灯光',
    'Curves': '曲线',
    'Cameras': '相机',
    'Resolution': '分辨率',
    'Scene Unit': '场景单位',
    "Apply current scene's unit (as defined by unit scale) to imported data": '将当前场景的单位（由单位比例定义）应用于导入的数据',
    'Forward Axis': '前进轴',
    'Up Axis': '向上轴',
    'Facet Normals': "面法线",
    'Is Sequence': "是序列",
    'Read the 3D cursor location': "读取3d游标位置",
    'Cursor Origin': "游标原点",
    "Use (import) facet normals (note that this will still give flat shading)":"使用（导入）面法线（请注意，这仍将产生平面着色）",
    'Import vertex color attributes':  "导入顶点颜色属性",
    'Vertex Colors': '顶点色',
    'Merges vertices by distance': '按距离合并顶点',
    'Merge Vertices': '合并顶点',
    'validate meshes': '验证网格',
    'Validate Meshes': '验证网格',
    'Validate and correct imported mesh (slow)': '验证和校正导入的网格（速度慢）',
    'Always Add Cache Reader': '始终添加缓存阅读器',
    'Add cache modifiers and constraints to imported objects even if they are not animated so that they can be updated when reloading the Alembic archive':'将缓存修改器和约束添加到导入的对象中，即使它们没有被动画化，这样它们在重新加载Alembic存档时也可以被更新',
    'import vertex groups': '导入顶点组',
    'use split groups': '使用拆分组',
    'use split objects': '使用拆分对象',
    'clamp size': '限制尺寸',
    'Bone Mapper': '骨骼映射',
    'Use blender bone name': '使用 Blender 骨骼名称',
    'Use japanese name of MMD bone': '使用MMD骨骼的日语名称',
    'Rename the bone of pose data to be blender suitable': '将骨骼姿势数据的名称修改为适合 Blender 的形式',
    'Rename Bones - L / R Suffix': '重命名骨骼 - 左 / 右后缀',
    'Use Blender naming conventions for Left / Right paired bones': '使用 Blender 命名约定处理左/右配对的骨骼',
    'Rename Bones - Use Underscore': '重命名骨骼 - 使用下划线',
    'Will not use dot, e.g. if renaming bones, will use _R instead of .R': '不使用点，例如在重命名骨骼时，将使用_R 而不是 .R',
    'Dictionary': '字典',
    'Disabled': '禁用',
    'Internal Dictionary': '内置字典',
    'Translate bone names from Japanese to English using selected dictionary':  "使用选定的字典将骨骼名称从日语翻译为英语",
    'Treat Current Pose as Rest Pose':  "将当前姿势视为初始姿势",
    'You can pose the model to fit the original pose of a pose data, such as T-Pose or A-Pose': "你可以调整模型的姿势，使其与姿势数据的原始姿势（例如 T-Pose 或 A-Pose）匹配",
    'Types': '类型',
    'Select which parts will be imported':  "选择将要导入的部分",
    'IK Loop Factor': 'IK 循环因子',
    'Scaling factor of MMD IK loop': "MMD IK 循环的缩放因子",
    'Mesh': '网格',
    'Armature': '网格',
    'Rigidbodies and joints (include Armature)': "刚体和关节（包括骨骼）",
    'Display frames (include Armature)': '显示帧（包括骨骼）',
    'Morphs (include Armature and Mesh)': '形变（包括骨骼和网格）"',
    'Clean Model': '清理模型',
    'Remove unused vertices and duplicated/invalid faces': "移除未使用的顶点和重复/无效的面",
    'Remove Doubles':  "移除重复顶点",
    'Fix IK Links':  "修复 IK 链接",
    'Fix IK links to be blender suitable':  "修复 IK 链接以适应 Blender",
    'Apply Bone Fixed Axis':  "应用骨骼固定轴",
    "Apply bone's fixed axis to be blender suitable":  "将骨骼的固定轴调整为适用于 Blender",
    'use MIP maps for UV textures':  "对UV纹理使用MIP贴图",
    'Specify if mipmaps will be generated': '指定是否生成MIP贴图',
    'Rename Bones To English':  "将骨骼重命名为英文",
    'influence of .sph textures': ".sph纹理的影响",
    'The diffuse color factor of texture slot for .sph textures': ".sph纹理的纹理槽漫反射颜色因子",
    'influence of .spa textures': '.spa纹理的影响',
    'The diffuse color factor of texture slot for .spa textures': ".spa纹理的纹理槽漫反射颜色因子",
    'Log level': '日志级别',
    'Select log level': '选择日志级别',
    'Create a log file': '创建日志',
    'Margin': '边距',
    'How many frames added before motion starting':  "动作开始前添加了多少帧",
    'Treat Current Pose as Rest Pose':"将当前姿势视为初始姿势",
    'You can pose the model to fit the original pose of a motion data, such as T-Pose or A-Pose': '你可以调整模型的姿势以适应运动数据的原始姿势，例如 T-Pose 或 A-Pose',
    'Mirror Motion': '镜像动作',
    'Import the motion by using X-Axis mirror': '通过使用X轴镜像导入动作',
    'Update scene settings': '更新场景设置',
    'Update frame range and frame rate (30 fps)': "更新帧范围和帧速率（30 fps）",
    'Import WebP textures':  "导入 WebP 纹理",
    'If a texture exists in WebP format,loads the WebP texture instead of the fallback PNG/JPEG one':"如果纹理以 WebP 格式存在，则加载 WebP 纹理，而不是备用的 PNG/JPEG 纹理",
    'Try to guess the original bind pose for skinned meshes from the inverse bind matrices.When off, use default/rest pose as bind pose':  "尝试从反向绑定矩阵中猜测蒙皮网格的原始绑定姿势。当关闭时，使用默认/静止姿势作为绑定姿势",
    'Guess Original Bind Pose': "猜测原始绑定姿势",
    'Heuristic for placing bones. Tries to make bones pretty': "放置骨骼的启发式方法。尝试使骨骼布局更加美观",
    'Bone Dir': '骨骼方向',
    'Good for re-importing glTFs exported from Blender, and re-exporting glTFs to glTFs after Blender editing.Bone tips are placed on their local +Y axis (in glTF space)': "适用于重新导入从Blender导出的glTF文件，并在Blender编辑后重新导出glTF文件。骨骼末端被放置在其本地 +Y 轴上（在glTF空间中）",
    'Decent all-around strategy. A bone with one child has its tip placed on the local axis closest to its child': "全面而可行的策略。具有一个子骨骼的骨骼，其末端被放置在最接近其子骨骼的本地轴上",
    "Might look better than Temperance, but also might have errors. A bone with one child has its tip placed at its child's root.Non-uniform scalings may get messed up though, so beware": "可能看起来比 Temperance 更好，但也可能存在错误。具有一个子骨骼的骨骼，其末端被放置在其子骨骼的根部。但非均匀缩放可能会出现问题，请注意",
    'How normals are computed during import': "在导入过程中如何计算法线",
    'Use Normal Data': "使用法线数据",
    'Flat Shading': "平面着色",
    'Smooth Shading': "平滑着色",
    'Shading': '着色',
    'The glTF format requires discontinuous normals, UVs, and other vertex attributes to be stored as separate vertices,as required for rendering on typical graphics hardware.This option attempts to combine co-located vertices where possible.Currently cannot combine verts with different normals':"glTF 格式要求将不连续的法线、UV 和其他顶点属性存储为单独的顶点，以适应典型的图形硬件渲染需求。此选项尝试在可能的情况下合并共位的顶点。目前无法合并具有不同法线的顶点",
    'Optional backwards compatibility for non-standard render engines. Applies to lights': "非标准渲染引擎的可选向后兼容性。适用于光源",
    'Blender lighting strengths with no conversion': "Blender照明强度，无需转换",
    'Non-physical, unitless lighting. Useful when exposure controls are not available': "非物理、无单位的照明。在无曝光控制时非常有用",
    'Physically-based glTF lighting units (cd, lx, nt)': '基于物理的glTF照明单位（cd，lx，nt）',
    'Lighting Mode': '灯光模式',
    'Pack Images': '打包图像',
    'Pack all images into .blend file': "将所有图像打包到 .blend 文件中",
    'Use pre/post rotation from FBX transform (you may have to disable that in some cases)': '使用来自FBX变换的前后旋转（在某些情况下可能需要禁用）',
    'Use Pre/Post Rotation': '使用前/后旋转',
    'Secondary Bone Axis': '次要骨骼轴',
    'Primary Bone Axis': '主要骨骼轴',
    'Try to align the major bone axis with the bone children': '尝试将主要骨骼轴与骨骼子级对齐',
    'Automatic Bone Orientation': '自动骨骼方向',
    'Force connection of children bones to their parent, even if their computed head/tail positions do not match (can be useful with pure-joints-type armatures)':"强制连接子骨骼到它们的父骨骼，即使它们的计算头部/尾部位置不匹配（在纯关节型骨骼中可能会有用）",
    'Force Connect Children': "强制连接子级",
    'Ignore the last bone at the end of each chain (used to mark the length of the previous bone)': "忽略每条链末端的最后一个骨骼（用于标记前一个骨骼的长度）",
    'Ignore Leaf Bones':"忽略末端骨骼",
    'Store enumeration values as strings': "将枚举值存储为字符串",
    "Import Enums As Strings":"将枚举值导入为字符串",
    'Import user properties as custom properties': "将用户属性导入为自定义属性",
    "Custom Properties": "自定义属性",
    'Import FBX subdivision information as subdivision surface modifiers':"将FBX细分信息导入为细分曲面修改器",
    'Subdivision Data': "细分数据",
    'Offset to apply to animation during import, in frames': "导入时应用于动画的偏移量，以帧为单位",
    'Animation Offset': "动画偏移",
    'Import FBX animation': "导入FBX动画",
    'Import Animation': '导入动画',
    'Displace geometry of alpha meshes': "位移alpha网格的几何形状",
    'Decal Offset': '贴花偏移',
    'Treat materials with alpha as decals (no shadow casting)':"将带有透明通道的材质视为贴花（不投射阴影）",
    'Alpha Decals': "Alpha贴花",
    'Search subdirs for any associated images (WARNING: may be slow)':"在子目录中搜索任何关联的图像文件（警告：可能较慢）",
    "Image Search": "图像搜索",
    'Custom Normals': "自定义法线",
    'Import custom normals, if available (otherwise Blender will recompute them)': "导入自定义法线，如果可用（否则Blender将重新计算它们）",
    "Bake space transform into object data, avoids getting unwanted rotations to objects when target space is not aligned with Blender's space (WARNING! experimental option, use at own risk, known to be broken with armatures/animations)": "将空间变换烘焙到对象数据中，避免在目标空间与Blender空间不对齐时，对象获得不必要的旋转（警告！实验性选项，使用需谨慎，已知在骨骼/动画中可能出现问题）",
    'Apply Transform': "应用变换",
    'Specify orientation and scale, instead of using embedded data in FBX file': "指定方向和缩放，而不使用FBX文件中的嵌入数据",
    'Manual Orientation': "手动方向",
    'Import options categories': "导入选项类别",
    'Main basic settings':"主要基本设置",
    'Armature-related settings': "与骨骼相关的设置",
    'Keep Bind Info': "保留绑定信息",
    'Store Bindpose information in custom bone properties for later use during Collada export': "将绑定姿势信息存储在自定义骨骼属性中，以备在导出Collada文件时后续使用",
    'Minimum Chain Length': "最小链长度",
    'When searching Bone Chains disregard chains of length below this value':"在搜索骨骼链时忽略长度低于此值的链",
    'Auto Connect': "自动连接",
    'Set use_connect for parent bones which have exactly one child bone':"为具有精确一个子骨骼的父骨骼设置 use_connect",
    'Find Bone Chains': "查找骨骼链",
    'Find best matching Bone Chains and ensure bones in chain are connected': "查找最佳匹配的骨骼链并确保链中的骨骼已连接",
    'Fix Leaf Bones':"修复末端骨骼",
    'Fix Orientation of Leaf Bones (Collada does only support Joints)': "修复末端骨骼的方向（Collada仅支持关节）",
    'Import Units': "导入单位",
    "If disabled match import to Blender's current Unit settings otherwise use the settings from the Imported scene": "如果禁用，则匹配导入到Blender当前的单位设置，否则使用导入场景的设置",
    'Convert rotations to quaternions': "将旋转转换为四元数",
    'Use the rotation order defined in the BVH file': "使用在BVH文件中定义的旋转顺序",
    'Convert rotations to euler XYZ': "将旋转转换为欧拉角XYZ",
    'Convert rotations to euler XZY': "将旋转转换为欧拉角XZY",
    'Convert rotations to euler YXZ': "将旋转转换为欧拉角YXZ",
    'Convert rotations to euler YZX': "将旋转转换为欧拉角YZX",
    'Convert rotations to euler ZXY': "将旋转转换为欧拉角ZXY",
    'Convert rotations to euler ZYX': '将旋转转换为欧拉角ZYX',
    'Loop the animation playback': "循环播放动画",
    'Loop': '循环',
    "Set the scene framerate to that of the BVH file (note that this nullifies the 'Scale FPS' option, as the scale will be 1:1)": "将场景的帧速率设置为BVH文件的帧速率（请注意，这会使 '缩放FPS' 选项无效，因为缩放将是1:1）",
    'Update Scene FPS': "更新场景帧速率",
    "Scale the framerate from the BVH to the current scenes, otherwise each BVH frame maps directly to a Blender frame":"将BVH的帧速率缩放到当前场景的帧速率，否则每个BVH帧直接映射到一个Blender帧",
    'Scale FPS': "缩放帧速率",
    'Starting frame for the animation':"动画的起始帧",
    'Start Frame': "起始帧",
    'Scale the BVH by this value': "以这个值来缩放BVH",
    'Import target type': "导入目标类型",
    'Target': "目标",
    "Update the scene's start and end frame to match those of the abc archive": '更新场景的起始帧和结束帧，使其与 abc归档的相匹配',
    'Manual Transform': "手动变换",
    # 'Meshes': '网格',
    # 'Meshes': '网格',
    # 'Meshes': '网格',
    # 'Meshes': '网格',
    # 'Meshes': '网格',
    'AIGODLIKE Community:cupcko': '幻之境：cupcko',

}
